apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: werewolf
resources:
  - api-deployment.yaml
  - reaper-deployment.yaml
  - judge-voice-worker-deployment.yaml
  - admin-deployment.yaml
  - services.yaml
configMapGenerator:
  - name: werewolf-api-config
    envs:
      - api.env
generatorOptions:
  disableNameSuffixHash: true
