apiVersion: v1
kind: Service
metadata:
  name: werewolf-api
  namespace: werewolf
spec:
  selector:
    app.kubernetes.io/name: werewolf-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: werewolf-mobile-web
  namespace: werewolf
spec:
  selector:
    app.kubernetes.io/name: werewolf-mobile-web
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: werewolf-admin-web
  namespace: werewolf
spec:
  selector:
    app.kubernetes.io/name: werewolf-admin-web
  ports:
    - name: http
      port: 8080
      targetPort: http
