apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: werewolf-staging
resources:
  - ../../base
  - ingress.yaml
images:
  - name: werewolf-api
    newName: ghcr.io/sixpigpig/werewolf-api
    newTag: sha-REPLACE_ME
  - name: werewolf-admin-web
    newName: ghcr.io/sixpigpig/werewolf-admin-web
    newTag: sha-REPLACE_ME
configMapGenerator:
  - name: werewolf-api-config
    behavior: replace
    envs:
      - api.env
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: Deployment
      name: werewolf-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: werewolf-admin-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
