export type RuleSetStatus = "draft" | "published" | "archived";
export type RuleRevisionState = "draft" | "published" | "superseded";
export type RuleRoleId = "werewolf" | "villager" | "seer" | "guard" | "witch" | "hunter" | "idiot";
export type RuleWinCondition = "wolves_gte_others" | "slaughter_side";
export type RuleSpeechPolicy = "sequential" | "sheriff_directed";
export type RuleBadgeBombPolicy = "none" | "double";
export type RuleWerewolfAttackResolution = "plurality_rotating_tiebreak" | "plurality_seeded_random" | "unanimous_no_attack";
export type RuleWerewolfAttackPolicy = { resolution: RuleWerewolfAttackResolution; allow_no_attack: boolean; allow_wolf_target: boolean };
export type RuleSetOptionSort = RuleSetSortField | `-${RuleSetSortField}`;
export type RuleSetConfig = { name: string; description: string; complexity: string; estimated_duration: string; rule_tags: string[]; role_counts: Record<RuleRoleId, number>; win_condition: RuleWinCondition; sheriff_enabled: boolean; sheriff_vote_weight: number; speech_policy: RuleSpeechPolicy; werewolf_self_explosion_enabled: boolean; first_night_last_words_enabled: boolean; sheriff_badge_bomb_policy: RuleBadgeBombPolicy; werewolf_attack_policy: RuleWerewolfAttackPolicy };
export type RuleSetUsage = { game_count: number; live_count: number };
export type RuleSetWarning = { code: string; path: string; message: string };
export type RuleClauseAudience = "player_public" | "role_private" | "internal_only";
export type RuleContractCoverage = "covered" | "broken";
export type RuleContractClause = {
  clause_id: string;
  priority: "P0" | "P1" | "P2";
  roles: string[];
  phases: string[];
  actions: string[];
  audience: RuleClauseAudience;
  engine_constraint_ids: string[];
  model_rule_text: string | null;
  coverage_status: RuleContractCoverage;
  uncovered_engine_constraint_ids: string[];
};
export type RuleContract = {
  schema_version: number;
  revision_id: string;
  canonical_hash: string;
  coverage_status: RuleContractCoverage;
  publish_ready: boolean;
  missing_p0_clause_ids: string[];
  broken_engine_constraint_ids: string[];
  clauses: RuleContractClause[];
};
export type RuleSetRevision = { id: string; rule_set_id: string; revision_no: number; state: RuleRevisionState; schema_version: number; content_hash: string | null; lock_version: number; config: RuleSetConfig | null; player_count: number; role_summary: string; created_at: string; updated_at: string; published_at: string | null; published_by: string | null };
export type RuleSetHistoryRevision = RuleSetRevision & { usage: RuleSetUsage };
export type AdminRuleSet = { id: string; status: RuleSetStatus; is_default: boolean; display_order: number; lock_version: number; draft_revision: RuleSetRevision | null; published_revision: RuleSetRevision | null; revisions: RuleSetRevision[]; created_at: string; updated_at: string };
export type AdminRuleSetDetail = Omit<AdminRuleSet, "revisions"> & { revisions: RuleSetHistoryRevision[]; usage: RuleSetUsage; warnings: RuleSetWarning[]; rule_contract: RuleContract | null };
export type AdminRuleSetList = { items: AdminRuleSet[]; pagination: { page: number; page_size: number; total: number; pages: number } };
export type RuleChoice<T extends string> = { value: T; label: string };
export type NonEmptyArray<T> = [T, ...T[]];
export type RuleSetOptions = { roles: NonEmptyArray<{ id: RuleRoleId; label: string; min_count: number; max_count: number }>; win_conditions: NonEmptyArray<RuleChoice<RuleWinCondition>>; sheriff_vote_weights: NonEmptyArray<number>; speech_policies: NonEmptyArray<RuleChoice<RuleSpeechPolicy>>; sheriff_badge_bomb_policies: NonEmptyArray<RuleChoice<RuleBadgeBombPolicy>>; werewolf_attack_resolutions: NonEmptyArray<RuleChoice<RuleWerewolfAttackResolution>>; statuses: NonEmptyArray<RuleChoice<RuleSetStatus>>; sorts: NonEmptyArray<RuleChoice<RuleSetOptionSort>>; constraints: { player_count_min: number; player_count_max: number; tags_max_items: number; tag_max_length: number; id_pattern: string; reason_min_length: number; reason_max_length: number } };
export type RuleSetValidationResponse = { valid: boolean; errors: RuleSetWarning[]; warnings: RuleSetWarning[]; compiled_snapshot: Record<string, unknown> | null; content_hash: string | null; rule_text_preview: string | null; rule_contract: RuleContract | null };
export type RuleSetValidation = Omit<RuleSetValidationResponse, "compiled_snapshot">;

export type RuleSetSortField = "display_order" | "updated_at" | "name" | "created_at";
export type RuleSetListParams = { page: number; page_size: number; q?: string; status?: RuleSetStatus; player_count?: number; sort: RuleSetSortField; direction: "asc" | "desc" };
export type CreateRuleSetRequest = { id: string; display_order: number; config: RuleSetConfig };
export type UpdateRuleSetDraftRequest = { expected_rule_set_lock_version: number; expected_revision_lock_version: number | null; display_order: number; config: RuleSetConfig };
export type ValidateRuleSetRequest = { expected_revision_lock_version: number };
export type PublishRuleSetRequest = { expected_rule_set_lock_version: number; expected_revision_lock_version: number; reason: string };
export type RuleSetTransitionRequest = { expected_rule_set_lock_version: number; reason: string };
export type ArchiveRuleSetRequest = RuleSetTransitionRequest & { replacement_default_rule_set_id: string | null; replacement_expected_lock_version: number | null };
export type SetDefaultRuleSetRequest = RuleSetTransitionRequest & { previous_default_expected_lock_version: number | null };
export type DuplicateRuleSetRequest = { expected_source_lock_version: number; new_rule_set_id: string; new_name: string };
