import type {
  AdminGameDebug,
  AdminGameDetail,
  AdminGameListItem,
  AdminGameModelRequestDetail,
  AdminGameModelRequestList,
} from "@/features/game-records/types";

export const contractRun = {
  run_id: "run_1234abcd",
  status: "completed",
  villager_model: "deepseek-v4-flash",
  werewolf_model: "doubao-seed-1-6-flash",
  max_rounds: 12,
  created_at: "2026-07-10T01:00:00Z",
  started_at: "2026-07-10T01:00:01Z",
  completed_at: "2026-07-10T01:03:00Z",
  event_count: 5,
  has_error: false,
} satisfies NonNullable<AdminGameListItem["latest_run"]>;

export const contractGameItem: AdminGameListItem = {
  session_id: "game_1234abcd",
  status: "complete",
  winner: "好人阵营",
  round_count: 1,
  resumable: false,
  rule_set: { id: "classic_8", name: "经典八人局", player_count: 8 },
  created_at: "2026-07-10T01:00:00Z",
  updated_at: "2026-07-10T01:03:00Z",
  latest_run: contractRun,
};

export const contractGameDetail: AdminGameDetail = {
  ...contractGameItem,
  players: [
    {
      seat: 1,
      name: "暮鸦归票",
      profile_id: "profile-1",
      model: "deepseek-v4-flash",
      role: "预言家",
      personality_id: "analytical",
      appearance_id: "default",
      avatar_image_url: "",
      tags: ["控场"],
    },
  ],
  rounds: [
    {
      number: 1,
      success: true,
      players: ["暮鸦归票"],
      public_summary: "首轮完成公开投票。",
      night_deaths: [
        { player: "雾灯听风", cause: null, source: null },
      ],
      day_deaths: [],
      exiled: "灰塔",
      hunter_shot: null,
      idiot_revealed: null,
      sheriff: "暮鸦归票",
      votes: { 暮鸦归票: "灰塔" },
      sheriff_elected: "暮鸦归票",
      werewolf_self_exploded: null,
      sheriff_candidates: ["暮鸦归票", "灰塔"],
      sheriff_withdrawn: ["灰塔"],
      sheriff_final_candidates: ["暮鸦归票"],
      sheriff_votes: { 雾灯听风: "暮鸦归票" },
      sheriff_pk_candidates: [],
      sheriff_runoff_votes: {},
      exile_pk_candidates: [],
      exile_runoff_votes: {},
      exile_resolution_reason: "first_vote_winner",
      sheriff_speech_order: ["暮鸦归票", "灰塔"],
      sheriff_speech_direction: "顺时针",
      speech_order: ["暮鸦归票", "灰塔"],
      speech_order_choice: "警右发言",
      sheriff_speeches: [
        { speaker: "暮鸦归票", message: "我会先听完大家的上警理由。" },
      ],
      sheriff_pk_speeches: [],
      exile_pk_speeches: [],
      debate: [
        { speaker: "暮鸦归票", message: "结合票型，我认为灰塔更可疑。" },
      ],
      sheriff_badge_target: null,
      sheriff_badge_lost: false,
      sheriff_badge_lost_reason: null,
      day_ended_by_self_explosion: false,
    },
  ],
  runs: [contractRun],
  recent_events: [
    {
      run_id: contractRun.run_id,
      event_id: 5,
      type: "game_completed",
      round: 1,
      phase: "summary",
      actor: null,
      action: null,
      created_at: "2026-07-10T01:03:00Z",
    },
  ],
  diagnostics: {
    run_count: 1,
    event_count: 5,
    failed_voice_count: 0,
    last_event: {
      run_id: contractRun.run_id,
      event_id: 5,
      type: "game_completed",
      round: 1,
      phase: "summary",
      actor: null,
      action: null,
      created_at: "2026-07-10T01:03:00Z",
    },
  },
  p2_quality: {
    schema_version: 1,
    data_status: "available",
    performance: {
      request_count: 24,
      discrete_action_sample_count: 18,
      discrete_action_p50_ms: 4200,
      discrete_action_p95_ms: null,
      discrete_action_max_ms: 13200,
      speech_first_token_sample_count: 8,
      speech_first_token_p95_ms: null,
      speech_first_token_max_ms: 7800,
      timeout_count: 1,
      fallback_count: 1,
      active_request_count: 0,
      game_duration_ms: 179000,
    },
    speech_quality: {
      checked_count: 8,
      retry_count: 2,
      exhausted_count: 0,
      low_novelty_window_count: 1,
    },
    choice_normalization: {
      exact_count: 20,
      seat_alias_count: 1,
      public_label_count: 3,
      invalid_count: 0,
      other_count: 0,
    },
    lineup_quality: {
      policy_mode: "repair",
      was_repaired: true,
      is_blocked: false,
      style_bucket_count: 4,
      required_style_bucket_count: 4,
      violations: [],
    },
    public_outcomes: [
      {
        schema_version: 1,
        round_number: 1,
        event_id: "outcome_fixture_1",
        sequence: 1,
        kind: "night_death",
        actor_player_id: null,
        target_player_id: "2号玩家",
        outcome: "eliminated",
        caused_by_event_id: null,
        occurred_phase: "night",
      },
      {
        schema_version: 1,
        round_number: 1,
        event_id: "outcome_fixture_2",
        sequence: 2,
        kind: "hunter_shot",
        actor_player_id: "2号玩家",
        target_player_id: "5号玩家",
        outcome: "eliminated",
        caused_by_event_id: "outcome_fixture_1",
        occurred_phase: "night",
      },
    ],
    public_outcome_summary_mismatch_count: 0,
    quality_gates: [
      {
        gate: "lineup",
        status: "pass",
        code: "lineup_passed",
        threshold: "无阻断违规",
        actual: "false",
      },
      {
        gate: "speech_quality",
        status: "pass",
        code: "speech_checked",
        threshold: "重写耗尽=0",
        actual: "0",
      },
      {
        gate: "performance",
        status: "warn",
        code: "insufficient_latency_sample",
        threshold: "离散动作P95<=15000ms且样本>=20",
        actual: "samples=18,p95=None",
      },
      {
        gate: "choice_normalization",
        status: "pass",
        code: "choice_checked",
        threshold: "invalid=0",
        actual: "0",
      },
      {
        gate: "public_outcomes",
        status: "pass",
        code: "outcome_summary_checked",
        threshold: "摘要不一致=0",
        actual: "0",
      },
    ],
  },
  quality_evaluation: {
    schema_version: 1,
    evaluator_version: "p3-v1",
    evaluation_status: "completed",
    data_status: "available",
    verdict: "warn",
    source_coverage: {
      state: "complete",
      logs: "complete",
      events: "complete",
      voice: "complete",
      subtitles: "complete",
      pending_voice_count: 0,
      failed_voice_count: 0,
    },
    issue_counts: { P0: 0, P1: 1, P2: 0 },
    facts: {
      critical_opportunity_count: 4,
      critical_recorded_count: 4,
      critical_fact_write_rate: 1,
      prompt_expected_critical_count: 8,
      prompt_included_critical_count: 8,
      prompt_missing_critical_count: 0,
      critical_fact_prompt_coverage_rate: 1,
      deterministic_contradiction_count: 0,
    },
    structure: {
      max_consecutive_self_explosions: 1,
      chain_three_count: 0,
      normal_day_debate_round_count: 1,
      sheriff_model_request_count: 2,
      public_model_request_count: 8,
      sheriff_model_request_rate: 0.25,
    },
    voice: {
      narratable_event_count: 5,
      effective_voice_event_count: 5,
      missing_narratable_event_count: 0,
      voice_coverage_rate: 1,
      voice_source_event_lag: 0,
      terminal_judge_voice_coverage: true,
      pending_voice_count: 0,
      failed_voice_count: 0,
      interruption_count: 1,
      replay_count: 1,
    },
    performance: {
      action_count: 24,
      action_duration_ms_max: 13200,
      action_duration_p95_ms: 12000,
      first_token_count: 20,
      first_token_ms_max: 7800,
      first_token_p95_ms: 8000,
      game_duration_ms: 179000,
      timeout_count: 1,
      retry_count: 2,
      fallback_count: 1,
    },
    content: {
      speech_check_count: 8,
      repeated_speech_count: 1,
      repeated_speech_rate: 0.125,
      speech_rewrite_count: 2,
      speech_rewrite_recovered_count: 2,
      speech_retry_exhausted_count: 0,
      privacy_p0_issue_count: 0,
      lineup_warning_count: 1,
    },
    evaluated_at: "2026-07-10T01:04:00Z",
  },
};

export const contractGameDebug: AdminGameDebug = {
  session_id: contractGameItem.session_id,
  game_error: "Maximum rounds exceeded",
  run_errors: [
    { run_id: contractRun.run_id, error: "Upstream request timed out" },
  ],
};

export const contractGameModelRequests: AdminGameModelRequestList = {
  session_id: contractGameItem.session_id,
  items: [
    {
      request_id: "req_contract_model_1",
      round_number: 1,
      phase: "day",
      actor: "暮鸦归票",
      action: "debate",
      model: "deepseek-v4-flash",
      status: "completed",
      attempt_count: 1,
      invalid_attempt_count: 0,
      run_id: contractRun.run_id,
      event_id: 4,
      created_at: "2026-07-10T01:02:00Z",
    },
    {
      request_id: "req_contract_model_2",
      round_number: 1,
      phase: "vote",
      actor: "雾灯听风",
      action: "vote",
      model: "doubao-seed-1-6-flash",
      status: "failed",
      attempt_count: 3,
      invalid_attempt_count: 1,
      run_id: contractRun.run_id,
      event_id: 5,
      created_at: "2026-07-10T01:02:30Z",
    },
  ],
};

export const contractGameModelRequestDetail: AdminGameModelRequestDetail = {
  ...contractGameModelRequests.items[0],
  prompt: "你正在进行一局狼人杀。请发表白天发言。",
  raw_response: '{"reasoning":"分析票型","say":"我会投给灰塔。"}',
  parsed_output: JSON.stringify(
    { reasoning: "分析票型", say: "我会投给灰塔。" },
    null,
    2,
  ),
  raw_choice: "我会投给灰塔。",
  error: null,
};
