apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: werewolf-admin-web
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - admin.example.com
      secretName: werewolf-admin-production-tls
  rules:
    - host: admin.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: werewolf-admin-web
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: werewolf-mobile-web
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - m.example.com
      secretName: werewolf-mobile-production-tls
  rules:
    - host: m.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: werewolf-mobile-web
                port:
                  name: http
