apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: werewolf-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: werewolf-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: werewolf-mobile-web
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: werewolf-mobile-web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: werewolf-admin-web
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: werewolf-admin-web
