apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: werewolf-staging
resources:
  - ../../../migration
images:
  - name: werewolf-api
    newName: ghcr.io/sixpigpig/werewolf-api
    newTag: sha-REPLACE_ME
